provider: {linux_aarch64: default, linux_ppc64le: default}
channels:
  targets:
    - [cctbx-dev, main]

azure:
  user_or_org: cctbx-release
  project_name: feedstock-builds
  store_build_artifacts: true
